### ISSUE TITLE
Lacking Docs

### ISSUE THREAD

**Issue by eyenx** [adfinis/ansible-role-users#5]
#### ISSUE TYPE

- Bug Report

#### SUMMARY

The README.md says "A brief description of the role goes here." and then goes on to contain generated default text.
#### STEPS TO REPRODUCE

Read docs.
#### EXPECTED RESULTS

Be informed.
#### ACTUAL RESULTS

No information.

**Comment by martinwe-adfinis** [comment]
Has been addressed with the revamp in https://github.com/adfinis/ansible-role-users/commit/08c31fb8e3585861a4311b16b791c0a0145465c0.

Closing as done.
